// Code generated by protoc-gen-go.
// source: sync.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SyncNotify struct {
	Offset           *int64 `protobuf:"varint,1,req,name=offset" json:"offset,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SyncNotify) Reset()                    { *m = SyncNotify{} }
func (m *SyncNotify) String() string            { return proto.CompactTextString(m) }
func (*SyncNotify) ProtoMessage()               {}
func (*SyncNotify) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *SyncNotify) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

type SyncReq struct {
	Offset           *int64 `protobuf:"varint,1,req,name=offset" json:"offset,omitempty"`
	Count            *int32 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SyncReq) Reset()                    { *m = SyncReq{} }
func (m *SyncReq) String() string            { return proto.CompactTextString(m) }
func (*SyncReq) ProtoMessage()               {}
func (*SyncReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *SyncReq) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *SyncReq) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type SyncRsp struct {
	Offset           *int64     `protobuf:"varint,1,req,name=offset" json:"offset,omitempty"`
	Messages         []*Message `protobuf:"bytes,2,rep,name=messages" json:"messages,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *SyncRsp) Reset()                    { *m = SyncRsp{} }
func (m *SyncRsp) String() string            { return proto.CompactTextString(m) }
func (*SyncRsp) ProtoMessage()               {}
func (*SyncRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *SyncRsp) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *SyncRsp) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*SyncNotify)(nil), "protocol.SyncNotify")
	proto.RegisterType((*SyncReq)(nil), "protocol.SyncReq")
	proto.RegisterType((*SyncRsp)(nil), "protocol.SyncRsp")
}

var fileDescriptor2 = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xae, 0xcc, 0x4b,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x52, 0xbc, 0xb9,
	0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x10, 0x09, 0x25, 0x19, 0x2e, 0xae, 0x60, 0xa0, 0x32, 0xbf,
	0xfc, 0x92, 0xcc, 0xb4, 0x4a, 0x21, 0x3e, 0x2e, 0xb6, 0xfc, 0xb4, 0xb4, 0xe2, 0xd4, 0x12, 0x09,
	0x46, 0x05, 0x26, 0x0d, 0x66, 0x25, 0x0d, 0x2e, 0x76, 0x90, 0x6c, 0x50, 0x6a, 0x21, 0xba, 0x94,
	0x10, 0x2f, 0x17, 0x6b, 0x72, 0x7e, 0x69, 0x5e, 0x89, 0x04, 0x93, 0x02, 0xa3, 0x06, 0xab, 0x92,
	0x1d, 0x54, 0x65, 0x71, 0x01, 0x86, 0x4a, 0x65, 0x2e, 0x0e, 0xa8, 0x9d, 0xc5, 0x40, 0xc5, 0xcc,
	0x1a, 0xdc, 0x46, 0x82, 0x7a, 0x30, 0xe7, 0xe8, 0xf9, 0x42, 0x64, 0x00, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x62, 0x91, 0x64, 0x2e, 0xad, 0x00, 0x00, 0x00,
}
